[package]
name = "lifelog"
version = "0.1.0"
edition = "2021"
description = "A project to log, process, and interact with various sources of data for your lifelog"

# Backend code has been moved to lifelog-interface/lifelog/src-tauri
# Check lifelog-interface/lifelog/src-tauri/Cargo.toml for dependencies

[workspace]
members = ["lifelog-interface/lifelog/src-tauri"]

# Dependencies have been moved to the Tauri project
[dependencies]

[features]
dev= []

[dev-dependencies]
anyhow = "1"
