lifelog_dir = "~/lifelog"

[screen]
enabled = true
interval = 1
program = "grim"
output_dir = "/home/matth/lifelog/data/screen"

[keyboard]
enabled = false
interval = 0.001
output_dir = "/home/matth/lifelog/data/keyboard"

[mouse]
enabled = false
interval = 0.001
output_dir = "/home/matth/lifelog/data/mouse"
