[package]
name = "transforms"
version = "0.1.0"
edition = "2021"

[dependencies]
thiserror = "2.0.12"
rusty-tesseract = "1.1.10"
utils = { path = "../utils" }
lifelog-core = {path = "../lifelog-core"}
lifelog-types = {path = "../lifelog-types"}
