name: "✨ Feature request"
about: "Suggest an idea or improvement."
title: "[Feature]: <short summary>"
labels: ["kind/feature", "status/needs-triage"]
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem
      description: "What pain point are you trying to solve?"
    # validations:
    #   required: false
  - type: textarea
    id: solution
    attributes:
      label: Proposed solution
      placeholder: "If you have a preferred approach, outline it."
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
  - type: textarea
    id: context
    attributes:
      label: Additional context / mock‑ups
