// Derives the Postgres migration set from `migrations/*.sql` at compile time and
// writes `$OUT_DIR/embedded_migrations.rs`, included by `src/postgres.rs`. Sweeping
// the directory instead of a hand-maintained list makes it impossible for a
// migration file to silently miss the runner (the MAT-1500 drift bug).
use std::env;
use std::fs;
use std::path::Path;

fn main() {
    let manifest_dir = env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR");
    let migrations_dir = Path::new(&manifest_dir).join("migrations");

    // Re-run if a file is added, removed, or edited in the migrations directory.
    println!("cargo:rerun-if-changed=migrations");

    let mut files: Vec<String> = fs::read_dir(&migrations_dir)
        .unwrap_or_else(|e| panic!("read migrations dir {}: {e}", migrations_dir.display()))
        .filter_map(|entry| entry.ok())
        .map(|entry| entry.file_name().to_string_lossy().into_owned())
        .filter(|name| name.ends_with(".sql"))
        .collect();
    // Filename order == chronological apply order (timestamp-prefixed names).
    files.sort();

    assert!(
        !files.is_empty(),
        "no *.sql files found in {}",
        migrations_dir.display()
    );

    let mut generated = String::from(
        "// @generated by build.rs — do not edit. Source: migrations/*.sql\n\
         const EMBEDDED_MIGRATIONS: &[EmbeddedMigration] = &[\n",
    );
    for name in &files {
        // include_str! resolves relative to OUT_DIR's included-file semantics, so
        // anchor each path at CARGO_MANIFEST_DIR to stay robust wherever the
        // generated file lands.
        generated.push_str(&format!(
            "    EmbeddedMigration {{ version: {name:?}, sql: include_str!(concat!(env!(\"CARGO_MANIFEST_DIR\"), \"/migrations/\", {name:?})) }},\n"
        ));
    }
    generated.push_str("];\n");

    let out_dir = env::var("OUT_DIR").expect("OUT_DIR");
    let dest = Path::new(&out_dir).join("embedded_migrations.rs");
    fs::write(&dest, generated).unwrap_or_else(|e| panic!("write {}: {e}", dest.display()));
}
