use std::{env, fs, path::Path};

// This build script looks at all of the data modalities that are define!
fn main() {
    // Re-run script if data-modalities directory changes
    //println!("cargo:rerun-if-changed=../../data-modalities");

    let out_dir = env::var("OUT_DIR").unwrap();
    let dest_path = Path::new(&out_dir).join("data_modalities.rs");

    // Get all modality directories
    let modalities = fs::read_dir("../data-modalities/src")
        .unwrap()
        .filter_map(|e| e.ok())
        .filter(|e| e.file_type().map(|t| t.is_dir()).unwrap_or(false))
        .map(|e| e.file_name().into_string().unwrap());

    // Generate enum variants
    let mut variants: Vec<String> = modalities
        .into_iter()
        .map(|name| {
            // Convert kebab-case to PascalCase
            name.split('-')
                .map(|word| {
                    let mut chars = word.chars();
                    match chars.next() {
                        None => String::new(),
                        Some(c) => c.to_uppercase().chain(chars).collect(),
                    }
                })
                .collect()
        })
        .collect();
    variants.sort();

    // Generate Rust code
    let code = format!(
        r#"// Auto-generated by build.rs
#[lifelog_type(None)]
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Deserialize, Serialize, EnumIter)]
pub enum DataModality {{
    {}
}}

impl DataModality {{
    pub fn tryfrom_str(name: &str) -> Result<Self, LifelogError> {{
        match name {{
            {}
            _ => Err(LifelogError::InvalidDataModality(name.to_string())),
        }}
    }}
    pub fn to_string(&self) -> String {{
        match self {{
            {}
        }}
    }}
}}
"#,
        variants.join(",\n    "),
        variants
            .iter()
            .map(|name| format!("\"{}\" => Ok(Self::{}),", name, name))
            .collect::<Vec<_>>()
            .join("\n            "),
        variants
            .iter()
            .map(|name| format!("Self::{} => \"{}\".to_string(),", name, name))
            .collect::<Vec<_>>()
            .join("\n            "),
    );

    fs::write(dest_path, code).unwrap();
}
