use lifelog_core::LifelogError;
use std::str::FromStr;
use tokio_postgres::NoTls;

pub type PostgresPool = deadpool_postgres::Pool;

pub fn is_postgres_uri(endpoint: &str) -> bool {
    let trimmed = endpoint.trim();
    trimmed.starts_with("postgres://") || trimmed.starts_with("postgresql://")
}

struct EmbeddedMigration {
    version: &'static str,
    sql: &'static str,
}

// `EMBEDDED_MIGRATIONS` is generated by build.rs, which sweeps every
// `migrations/*.sql` file (sorted by filename == apply order). Deriving the set
// from the directory makes it impossible for a migration file to silently miss
// the runner, the drift bug this replaced (MAT-1500).
include!(concat!(env!("OUT_DIR"), "/embedded_migrations.rs"));

fn is_unix_socket_connection(cfg: &tokio_postgres::Config) -> bool {
    let hosts = cfg.get_hosts();
    if hosts.is_empty() {
        return true;
    }
    hosts
        .iter()
        .all(|h| matches!(h, tokio_postgres::config::Host::Unix(_)))
}

pub async fn connect_pool(
    database_url: &str,
    max_connections: usize,
) -> Result<PostgresPool, LifelogError> {
    tracing::debug!("Connecting to Postgres with URI: {}", database_url);
    let cfg =
        tokio_postgres::Config::from_str(database_url).map_err(|e| LifelogError::Validation {
            field: "database_endpoint".to_string(),
            reason: format!("invalid postgres uri: {e}"),
        })?;

    if !is_unix_socket_connection(&cfg) {
        tracing::warn!(
            "PostgreSQL connection uses TCP without TLS. \
             Use a Unix socket or add a TLS connector crate for production deployments."
        );
    }

    let mgr_cfg = deadpool_postgres::ManagerConfig {
        recycling_method: deadpool_postgres::RecyclingMethod::Fast,
    };
    let mgr = deadpool_postgres::Manager::from_config(cfg, NoTls, mgr_cfg);
    deadpool_postgres::Pool::builder(mgr)
        .max_size(max_connections)
        .build()
        .map_err(|e| LifelogError::Database(format!("postgres pool build failed: {e}")))
}

pub async fn run_migrations(pool: &PostgresPool) -> Result<(), LifelogError> {
    let mut client = match pool.get().await {
        Ok(c) => c,
        Err(e) => {
            tracing::error!("Postgres pool get failed during migrations: {e}");
            return Err(LifelogError::Database(format!(
                "postgres pool get failed: {e}"
            )));
        }
    };
    client
        .batch_execute(
            "CREATE TABLE IF NOT EXISTS schema_migrations (
                version TEXT PRIMARY KEY,
                applied_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
            );",
        )
        .await
        .map_err(|e| LifelogError::Database(format!("postgres migration bootstrap failed: {e}")))?;

    for migration in EMBEDDED_MIGRATIONS {
        let already = client
            .query_opt(
                "SELECT version FROM schema_migrations WHERE version = $1",
                &[&migration.version],
            )
            .await
            .map_err(|e| LifelogError::Database(format!("migration query failed: {e}")))?;
        if already.is_some() {
            continue;
        }

        let tx = client
            .transaction()
            .await
            .map_err(|e| LifelogError::Database(format!("migration tx begin failed: {e}")))?;
        tx.batch_execute(migration.sql).await.map_err(|e| {
            LifelogError::Database(format!("apply migration {} failed: {e}", migration.version))
        })?;
        tx.execute(
            "INSERT INTO schema_migrations(version) VALUES ($1)",
            &[&migration.version],
        )
        .await
        .map_err(|e| {
            LifelogError::Database(format!(
                "record migration {} failed: {e}",
                migration.version
            ))
        })?;
        tx.commit().await.map_err(|e| {
            LifelogError::Database(format!(
                "commit migration {} failed: {e}",
                migration.version
            ))
        })?;
    }

    // Startup assertion: every embedded migration must now be recorded. Guards
    // against a runner regression silently leaving the schema partially migrated
    // (the MAT-1500 class), so the server refuses to serve on a drifted DB.
    let recorded = client
        .query("SELECT version FROM schema_migrations", &[])
        .await
        .map_err(|e| LifelogError::Database(format!("schema_migrations read-back failed: {e}")))?;
    let recorded: std::collections::HashSet<String> =
        recorded.iter().map(|row| row.get::<_, String>(0)).collect();
    let missing: Vec<&str> = EMBEDDED_MIGRATIONS
        .iter()
        .map(|m| m.version)
        .filter(|v| !recorded.contains(*v))
        .collect();
    if !missing.is_empty() {
        return Err(LifelogError::Database(format!(
            "migration drift after apply: {} embedded migration(s) not recorded: {}",
            missing.len(),
            missing.join(", ")
        )));
    }

    Ok(())
}

#[cfg(test)]
mod tests {
    use super::{is_postgres_uri, EMBEDDED_MIGRATIONS};

    /// Guards against the MAT-1500 drift class: every `migrations/*.sql` file
    /// must be present in the runner's set, and vice versa. build.rs already
    /// derives the set from the directory, so this is a regression backstop in
    /// case the derivation is ever replaced by a hand-maintained list again.
    #[test]
    fn every_migration_file_is_registered() {
        let dir = concat!(env!("CARGO_MANIFEST_DIR"), "/migrations");
        let mut on_disk: Vec<String> = std::fs::read_dir(dir)
            .expect("read migrations dir")
            .filter_map(|e| e.ok())
            .map(|e| e.file_name().to_string_lossy().into_owned())
            .filter(|n| n.ends_with(".sql"))
            .collect();
        on_disk.sort();

        let mut registered: Vec<String> = EMBEDDED_MIGRATIONS
            .iter()
            .map(|m| m.version.to_string())
            .collect();
        registered.sort();

        assert_eq!(
            on_disk, registered,
            "migration drift: files in migrations/ differ from the runner's registered set"
        );
    }

    /// Runner applies in slice order; timestamp-prefixed filenames must be sorted
    /// so apply order is chronological.
    #[test]
    fn registered_migrations_are_sorted() {
        let versions: Vec<&str> = EMBEDDED_MIGRATIONS.iter().map(|m| m.version).collect();
        let mut sorted = versions.clone();
        sorted.sort_unstable();
        assert_eq!(versions, sorted, "migrations must be in sorted apply order");
    }

    #[test]
    fn detects_postgres_uris() {
        assert!(is_postgres_uri("postgres://user:pass@localhost/lifelog"));
        assert!(is_postgres_uri("postgresql://user:pass@localhost/lifelog"));
    }

    #[test]
    fn rejects_non_postgres_uris() {
        assert!(!is_postgres_uri("127.0.0.1:7183"));
        assert!(!is_postgres_uri("ws://127.0.0.1:7183"));
        assert!(!is_postgres_uri("http://localhost:5432"));
    }
}
