use lifelog_core::LifelogError;
use std::str::FromStr;
use tokio_postgres::NoTls;

pub type PostgresPool = deadpool_postgres::Pool;

pub fn is_postgres_uri(endpoint: &str) -> bool {
    let trimmed = endpoint.trim();
    trimmed.starts_with("postgres://") || trimmed.starts_with("postgresql://")
}

struct EmbeddedMigration {
    version: &'static str,
    sql: &'static str,
}

// `EMBEDDED_MIGRATIONS` is generated by build.rs, which sweeps every
// `migrations/*.sql` file (sorted by filename == apply order). Deriving the set
// from the directory makes it impossible for a migration file to silently miss
// the runner, the drift bug this replaced (MAT-1500).
include!(concat!(env!("OUT_DIR"), "/embedded_migrations.rs"));

fn is_unix_socket_connection(cfg: &tokio_postgres::Config) -> bool {
    let hosts = cfg.get_hosts();
    if hosts.is_empty() {
        return true;
    }
    hosts
        .iter()
        .all(|h| matches!(h, tokio_postgres::config::Host::Unix(_)))
}

pub async fn connect_pool(
    database_url: &str,
    max_connections: usize,
) -> Result<PostgresPool, LifelogError> {
    tracing::debug!("Connecting to Postgres with URI: {}", database_url);
    let cfg =
        tokio_postgres::Config::from_str(database_url).map_err(|e| LifelogError::Validation {
            field: "database_endpoint".to_string(),
            reason: format!("invalid postgres uri: {e}"),
        })?;

    if !is_unix_socket_connection(&cfg) {
        tracing::warn!(
            "PostgreSQL connection uses TCP without TLS. \
             Use a Unix socket or add a TLS connector crate for production deployments."
        );
    }

    let mgr_cfg = deadpool_postgres::ManagerConfig {
        recycling_method: deadpool_postgres::RecyclingMethod::Fast,
    };
    let mgr = deadpool_postgres::Manager::from_config(cfg, NoTls, mgr_cfg);
    deadpool_postgres::Pool::builder(mgr)
        .max_size(max_connections)
        .build()
        .map_err(|e| LifelogError::Database(format!("postgres pool build failed: {e}")))
}

pub async fn run_migrations(pool: &PostgresPool) -> Result<(), LifelogError> {
    let mut client = match pool.get().await {
        Ok(c) => c,
        Err(e) => {
            tracing::error!("Postgres pool get failed during migrations: {e}");
            return Err(LifelogError::Database(format!(
                "postgres pool get failed: {e}"
            )));
        }
    };
    client
        .batch_execute(
            "CREATE TABLE IF NOT EXISTS schema_migrations (
                version TEXT PRIMARY KEY,
                applied_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
            );",
        )
        .await
        .map_err(|e| LifelogError::Database(format!("postgres migration bootstrap failed: {e}")))?;

    for migration in EMBEDDED_MIGRATIONS {
        let already = client
            .query_opt(
                "SELECT version FROM schema_migrations WHERE version = $1",
                &[&migration.version],
            )
            .await
            .map_err(|e| LifelogError::Database(format!("migration query failed: {e}")))?;
        if already.is_some() {
            continue;
        }

        let tx = client
            .transaction()
            .await
            .map_err(|e| LifelogError::Database(format!("migration tx begin failed: {e}")))?;
        tx.batch_execute(migration.sql).await.map_err(|e| {
            LifelogError::Database(format!("apply migration {} failed: {e}", migration.version))
        })?;
        tx.execute(
            "INSERT INTO schema_migrations(version) VALUES ($1)",
            &[&migration.version],
        )
        .await
        .map_err(|e| {
            LifelogError::Database(format!(
                "record migration {} failed: {e}",
                migration.version
            ))
        })?;
        tx.commit().await.map_err(|e| {
            LifelogError::Database(format!(
                "commit migration {} failed: {e}",
                migration.version
            ))
        })?;
    }

    // Startup consistency check: the DB's applied-migration set must match what
    // this binary knows about, or refuse to serve on a drifted DB (MAT-1500 class).
    verify_migration_consistency(&client).await?;

    Ok(())
}

/// Verifies the DB's applied-migration set is consistent with this binary's
/// embedded set. `run_migrations` calls this after applying.
///
/// Two directions, handled differently on purpose:
///
/// - **DB ahead of this binary** — `schema_migrations` holds a version this build
///   doesn't know, i.e. the DB was migrated by a *newer* build. This is expected
///   during an emergency binary rollback, so we **warn loudly and continue** rather
///   than refuse to boot (a refusal would force fix-forward on every incident). The
///   running code may not understand newer schema changes, hence the error-level
///   noise. (A fail-closed config flag could be added later if wanted.)
/// - **Embedded migration not recorded** — the apply loop guarantees this can't
///   happen, so a violation means the runner itself is broken. **Fail closed** (Err).
pub async fn verify_migration_consistency(
    client: &deadpool_postgres::Client,
) -> Result<(), LifelogError> {
    let rows = client
        .query("SELECT version FROM schema_migrations", &[])
        .await
        .map_err(|e| LifelogError::Database(format!("schema_migrations read-back failed: {e}")))?;
    let recorded: std::collections::HashSet<String> =
        rows.iter().map(|row| row.get::<_, String>(0)).collect();
    let embedded: std::collections::HashSet<&str> =
        EMBEDDED_MIGRATIONS.iter().map(|m| m.version).collect();

    // DB ahead of this binary (migrated by a newer build): warn loudly, keep going.
    let mut unknown: Vec<&str> = recorded
        .iter()
        .map(String::as_str)
        .filter(|v| !embedded.contains(v))
        .collect();
    if !unknown.is_empty() {
        unknown.sort_unstable();
        tracing::error!(
            "DATABASE IS AHEAD OF THIS SERVER BUILD: {} applied migration(s) are unknown to this \
             binary: {}. This binary is running BEHIND the schema — likely a rollback to an older \
             build. Continuing, but the running code may not understand newer schema changes.",
            unknown.len(),
            unknown.join(", ")
        );
        tracing::error!(
            "SCHEMA DRIFT: server is running BEHIND the database schema by {} migration(s); \
             confirm this is an intentional rollback.",
            unknown.len()
        );
    }

    // Embedded migration not recorded: the apply loop guarantees this can't happen,
    // so a violation means the runner is broken. Fail closed.
    let mut missing: Vec<&str> = EMBEDDED_MIGRATIONS
        .iter()
        .map(|m| m.version)
        .filter(|v| !recorded.contains(*v))
        .collect();
    if !missing.is_empty() {
        missing.sort_unstable();
        return Err(LifelogError::Database(format!(
            "migration drift: {} embedded migration(s) not recorded (the runner is broken): {}",
            missing.len(),
            missing.join(", ")
        )));
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::{is_postgres_uri, EMBEDDED_MIGRATIONS};

    /// Guards against the MAT-1500 drift class: every `migrations/*.sql` file
    /// must be present in the runner's set, and vice versa. build.rs already
    /// derives the set from the directory, so this is a regression backstop in
    /// case the derivation is ever replaced by a hand-maintained list again.
    #[test]
    fn every_migration_file_is_registered() {
        let dir = concat!(env!("CARGO_MANIFEST_DIR"), "/migrations");
        let mut on_disk: Vec<String> = std::fs::read_dir(dir)
            .expect("read migrations dir")
            .filter_map(|e| e.ok())
            .map(|e| e.file_name().to_string_lossy().into_owned())
            .filter(|n| n.ends_with(".sql"))
            .collect();
        on_disk.sort();

        let mut registered: Vec<String> = EMBEDDED_MIGRATIONS
            .iter()
            .map(|m| m.version.to_string())
            .collect();
        registered.sort();

        assert_eq!(
            on_disk, registered,
            "migration drift: files in migrations/ differ from the runner's registered set"
        );
    }

    /// Runner applies in slice order; timestamp-prefixed filenames must be sorted
    /// so apply order is chronological.
    #[test]
    fn registered_migrations_are_sorted() {
        let versions: Vec<&str> = EMBEDDED_MIGRATIONS.iter().map(|m| m.version).collect();
        let mut sorted = versions.clone();
        sorted.sort_unstable();
        assert_eq!(versions, sorted, "migrations must be in sorted apply order");
    }

    #[test]
    fn detects_postgres_uris() {
        assert!(is_postgres_uri("postgres://user:pass@localhost/lifelog"));
        assert!(is_postgres_uri("postgresql://user:pass@localhost/lifelog"));
    }

    #[test]
    fn rejects_non_postgres_uris() {
        assert!(!is_postgres_uri("127.0.0.1:7183"));
        assert!(!is_postgres_uri("ws://127.0.0.1:7183"));
        assert!(!is_postgres_uri("http://localhost:5432"));
    }
}
